### DISCUSSION TITLE
No match was found for the specified search criteria and module name

### DISCUSSION THREAD

**Discussion by WhoDunDidIt** [bagetter/BaGetter#225] [Q&A]
I am unable to search for, or install any module by name.

I am able to search for them via a wildcard, but any attempt to install via their proper name fails with No match found.

Any ideas?

Compose file:

```
services:
  bagetter:
    image: bagetter/bagetter:latest
    volumes:
      # Single file mounted for API key
      - ./secrets/api-key.txt:/run/secrets/ApiKey:ro
      - ./data:/srv/baget
    ports:
      - "5000:8080"
    environment:
      - Database__ConnectionString=Data Source=/srv/baget/bagetter.db
      - Database__Type=Sqlite
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://api.nuget.org/v3/index.json
      - Storage__Type=FileSystem
      - Storage__Path=/srv/baget/packages
      - Statistics__EnableStatisticsPage=false
      - Statistics__ListConfiguredServices=false
  ```

```
 USER:user .\WindowsPowerShell\  Monday 7:17:51 PM
[0.03s] > Install-Module -Name LoggingTwo -Repository myreponame
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'LoggingTwo'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:9711 char:34
+ ... talledPackages = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage


 USER:user .\WindowsPowerShell\  Monday 7:17:56 PM
[0.55s] > Find-module LoggingTwo -Repository myreponame          
PackageManagement\Find-Package : No match was found for the specified search criteria and module name 'LoggingTwo'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\2.2.5\PSModule.psm1:8879 char:9
+         PackageManagement\Find-Package @PSBoundParameters | Microsoft ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...ets.FindPackage:FindPackage) [Find-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.FindPackage       
 

 USER:user .\WindowsPowerShell\  Monday 7:21:20 PM 
[0.67s] > Find-module LoggingT* -Repository myreponame 

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.0.0                LoggingTwo                          myreponame               Standardized logging module
```
