### DISCUSSION TITLE
Mirror and docker compose

### DISCUSSION THREAD

**Discussion by RainerMueller82** [bagetter/BaGetter#80] [Q&A] [answered]
Hi,

I would like to enable the Nuget.org mirroring, but it looks like it is not working. I've the following compose yml

When running the docker container and searching for any nuget packages it does not find and show packages from nuget.org.

any hints how to solve this?

```
version: '2'

services:
  bagetter:
    image: bagetter/bagetter:latest
    ports:
      - "8099:8080"
    volumes:
      # Single file mounted for API key
      - ./secrets/api-key.txt:/run/secrets/ApiKey:ro
      - ./data:/srv/baget
    environment:
      - Database__ConnectionString=Data Source=/srv/baget/bagetter.db
      - Database__Type=Sqlite
      - Mirror__Enabled=true
      - Mirror__PackageSource=https://api.nuget.org/v3/index.json
      - Storage__Type=FileSystem
      - Storage__Path=/srv/baget/packages
```
