### ISSUE TITLE
Symbols server page returning 404

### ISSUE THREAD

**Issue by vh54** [bagetter/BaGetter#154]
### Describe the bug
I've uploaded a nupkg and a snupkg but I can't consult or autoload the symbols via the url in the documentation.

on page https://www.bagetter.com/docs/Installation/docker it is stated http://<url>/api/download/symbols
but it always returns 404

```
root@buildmachine:/root # dockerps
bagetter/bagetter:latest           bagetter                    Up 21 minutes  2024-06-12 16:58:56 +0200 CEST 0.0.0.0:4444->8080/tcp, :::4444->8080/tcp
```

```
√root@buildmachine:/root # curl http://localhost:4444/api/v2/symbol -kv
*   Trying 127.0.0.1:4444...
* Connected to localhost (127.0.0.1) port 4444 (#0)
> GET /api/v2/symbol HTTP/1.1
> Host: localhost:4444
> User-Agent: curl/7.81.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Length: 0
< Date: Wed, 12 Jun 2024 13:26:21 GMT
< Server: Kestrel
<
```

### To Reproduce
```
root@buildmachine:/agu/bagetter # find data
data
data/baget.db
data/packages
data/packages/packages
data/packages/packages/factsdataobjects
data/packages/packages/factsdataobjects/4.9.9
data/packages/packages/factsdataobjects/4.9.9/factsdataobjects.4.9.9.nupkg
data/packages/packages/factsdataobjects/4.9.9/factsdataobjects.nuspec
data/packages/symbols
data/packages/symbols/factsdataobjects.pdb
data/packages/symbols/factsdataobjects.pdb/7dc8b3ca5b174bd1a0a6400423cf5b90ffffffff
```
```
root@buildmachine:/agu/bagetter # cat bagetter.yml
version: '3.8'

services:
  nuget-server:
    image: bagetter/bagetter:latest
    container_name: bagetter
    restart: unless-stopped
    ports:
      - "4444:8080"
    env_file:
      - bagetter.env
    environment:
      - BaseURL=https://bagetter.foo.com/
    volumes:
      - ./data:/data
```

```
root@buildmachine:/agu/bagetter # cat bagetter.env
# The following config is the API Key used to publish packages.
# You should change this to a secret value to secure your server.
ApiKey=foo
Storage__Type=FileSystem
Storage__Path=/data/packages
Database__Type=Sqlite
Database__ConnectionString=Data Source=/data/baget.db
Search__Type=Database
AllowPackageOverwrites=true
Symbols__Enabled=true 
```

### Expected behavior
Not a 404 but a usefull where symbols could be looked up
