### ISSUE TITLE
read-through caching using docker on wsl

### ISSUE THREAD

**Issue by martenf** [bagetter/BaGetter#163]
I'm trying to run BaGetter as a docker container using docker compose on wsl.
I can't seam to mount the appsettings.json file to a volume and so I tried as a temporary solution to enable read-through caching in the appsettings.json file. When I do that and restart the docker container I still can't find any nuget.org packages in the web interface.

```
volumes:
  data:

services:
  bagetter:
    image: bagetter/bagetter:latest
    environment:
    - ApiKey=APIKEY
    restart: unless-stopped
    volumes:
    - data:/data
    ports:
    - 5000:8080

```

- For docker use it would be very convenient to have the settings files in a separate settings folder and not inside the app folder.
- Is it possible to enable read-through caching with an environmental variable?
- With the docker compose code above should the read-through caching work after enabling it in the appsettings.json or am I missing something?
