### ISSUE TITLE
app settings.json not honoring database configuration

### ISSUE THREAD

**Issue by RachelAmbler** [bagetter/BaGetter#197]
### Describe the bug
`appsettings.json` not honoring database configuration. Unsure yet if it's honoring other sections.

### To Reproduce
```json
{
  "PackageDeletionBehavior": "Unlist",
  "AllowPackageOverwrites": false,
  "MaxPackageSizeGiB": 8,
  "Database": {
    "Type": "PostgreSql",
    "ConnectionString": "Server=myDbServer;Port=5432;Database=bagetter;User Id=bagetter;Password=myPassword"
  },
  "Storage": {
    "Type": "FileSystem",
    "Path": ""
  },
  "Search": {
    "Type": "Database"
  },
  "Mirror": {
    "Enabled": true,
    "PackageSource": "https://api.nuget.org/v3/index.json"
  },
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Warning"
      }
    },
    "Console": {
      "LogLevel": {
        "Microsoft.Hosting.Lifetime": "Debug",
        "Default": "Warning"
      }
    }
  },
  "HealthCheck": {
    "Path": "/health"
  },
  "Statistics": {
    "EnableStatisticsPage": true,
    "ListConfiguredServices": true
  },
  "Authentication": {
    "ApiKeys": [
      {
        "Key": "myApiKey"
      }
    ],
    "Credentials": [
      {
        "Username": "Admin",
        "Password": "myPassword2"
      }
    ]
  }
}
```
### Expected behavior
For BaGetter to connect to my PostgreSql server

### Additional context
It connects just fine if I use environment variables. I know the `appsettings.json` file is being read because if I change one of the `Logging` options to an invalid logging type (e.g. `Invalid`)  then I get exceptions as a result.

To further debug, I also changed `ConnectionString` to `xconnectionString` - this should also result in an exception as `ConnectionString` is decorated with the `[Required]` attribute. However no such event happens.

I'm also unsure if the auth piece is working as I've yet to get to that section but, as it stands, I'm able to hit the web page directly with no auth challenges.

`docker-compose.yml`:
```yaml
services:
  NGinx:
    container_name: baGetter-Nginx
    image: nginx:latest
    restart: unless-stopped
    networks:
      - baGetterNet
    ports:
      - "1443:1443"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
        - /etc/ssl/certs/CorpBundle.pem:/etc/ssl/certs/site.crt
        - /etc/ssl/private/CorpPrivateKey.pem:/etc/ssl/private/site.key
        - ./nginx/private/PrivateKey-Protected.key:/etc/ssl/private/site.fifo
        - ./nginx/access.log:/var/log/nginx/access.log
        - ./nginx/error.log:/var/log/nginx/error.log
    depends_on:
      - baGetter
  baGetter:
    container_name: baGetter
    image: bagetter/bagetter:latest
    volumes:
      - data:/data
      - ./appsettings.json:/app/appsettings.json
    restart: always
    networks:
      - baGetterNet
volumes:
  data:
networks:
  baGetterNet:
```
