### ISSUE TITLE
Nuget packages not visible anymore in the web ui 

### ISSUE THREAD

**Issue by lo-yuta** [bagetter/BaGetter#87]
### Describe the bug
after a docker compos down --remove-orphan and a docker compose up -d , the nuget packages are present inside host's packages folder but not visible in the UI anymore.

### To Reproduce
1. Using this version of BaGetter 1.0.4
2. run the following docker-compose:
```
version: '3.8'

services:
bagetter:
    image: bagetter/bagetter:${Baget_Version}
    env_file:
      - .env
    volumes:
      - /mnt/packages_storage:/srv/baget
      - ${PWD}/baget/conf/appsettings.json:/app/appsettings.json:ro
```
and the following .env var file
```
Baget_Version='1.0.4'
Database__ConnectionString=Data Source=//baget/bagetter.db
Database__Type=Sqlite
Mirror__Enabled=false
Storage__Type=FileSystem
Storage__Path=/srv/baget/packages
```

### Expected behavior
we should expect that the package is visible on the web ui.

### Screenshots
![image](https://github.com/bagetter/BaGetter/assets/77937738/64cae648-c513-4170-aded-f950c02174fc)
![image](https://github.com/bagetter/BaGetter/assets/77937738/673e9237-b0ed-40ea-ae11-f99b4291af52)
